In [1]:
print ("Hello world")

Hello world

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\Cr7RE\\OneDrive\\Desktop\\Git Project\\Project_1'

In [4]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'Data_exp.ipynb',
 'example.txt',
 'example_2.txt',
 'iris_csv.csv',
 'mcg440_prog5_solution.py',
 'README.md',
 'Untitled.ipynb']

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv( 'iris_csv.csv')

In [7]:
df

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
df.head()

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [9]:
df.tail()

     sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [10]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [11]:
df.loc[5:10,['sepallength', 'sepalwidth', 'petallength']]

    sepallength  sepalwidth  petallength
5           5.4         3.9          1.7
6           4.6         3.4          1.4
7           5.0         3.4          1.5
8           4.4         2.9          1.4
9           4.9         3.1          1.5
10          5.4         3.7          1.5

In [12]:
df['class']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

In [13]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [14]:
setosa = df[df['class'] == 'Iris-setosa']

In [15]:
setosa

    sepallength  sepalwidth  petallength  petalwidth        class
0           5.1         3.5          1.4         0.2  Iris-setosa
1           4.9         3.0          1.4         0.2  Iris-setosa
2           4.7         3.2          1.3         0.2  Iris-setosa
3           4.6         3.1          1.5         0.2  Iris-setosa
4           5.0         3.6          1.4         0.2  Iris-setosa
5           5.4         3.9          1.7         0.4  Iris-setosa
6           4.6         3.4          1.4         0.3  Iris-setosa
7           5.0         3.4          1.5         0.2  Iris-setosa
8           4.4         2.9          1.4         0.2  Iris-setosa
9           4.9         3.1          1.5         0.1  Iris-setosa
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa
20          5.4         3.4          1.7         0.2  Iris-setosa
21          5.1         3.7          1.5         0.4  Iris-setosa
22          4.6         3.6          1.0         0.2  Iris-setosa
23          5.1         3.3          1.7         0.5  Iris-setosa
24          4.8         3.4          1.9         0.2  Iris-setosa
25          5.0         3.0          1.6         0.2  Iris-setosa
26          5.0         3.4          1.6         0.4  Iris-setosa
27          5.2         3.5          1.5         0.2  Iris-setosa
28          5.2         3.4          1.4         0.2  Iris-setosa
29          4.7         3.2          1.6         0.2  Iris-setosa
30          4.8         3.1          1.6         0.2  Iris-setosa
31          5.4         3.4          1.5         0.4  Iris-setosa
32          5.2         4.1          1.5         0.1  Iris-setosa
33          5.5         4.2          1.4         0.2  Iris-setosa
34          4.9         3.1          1.5         0.1  Iris-setosa
35          5.0         3.2          1.2         0.2  Iris-setosa
36          5.5         3.5          1.3         0.2  Iris-setosa
37          4.9         3.1          1.5         0.1  Iris-setosa
38          4.4         3.0          1.3         0.2  Iris-setosa
39          5.1         3.4          1.5         0.2  Iris-setosa
40          5.0         3.5          1.3         0.3  Iris-setosa
41          4.5         2.3          1.3         0.3  Iris-setosa
42          4.4         3.2          1.3         0.2  Iris-setosa
43          5.0         3.5          1.6         0.6  Iris-setosa
44          5.1         3.8          1.9         0.4  Iris-setosa
45          4.8         3.0          1.4         0.3  Iris-setosa
46          5.1         3.8          1.6         0.2  Iris-setosa
47          4.6         3.2          1.4         0.2  Iris-setosa
48          5.3         3.7          1.5         0.2  Iris-setosa
49          5.0         3.3          1.4         0.2  Iris-setosa

In [16]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')